# py C:\Users\Schipilliti_A\Documents\bunker-tool\generate_twstats_village_map.py --start 1 --end 100 --out villages.js

from __future__ import annotations

import argparse
import re
import time
from pathlib import Path

import requests
from bs4 import BeautifulSoup


def fetch_soup(url: str, timeout: int) -> BeautifulSoup:
    response = requests.get(
        url,
        timeout=timeout,
        headers={
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) TW bunker planner",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        },
    )
    response.raise_for_status()
    return BeautifulSoup(response.text, "html.parser")


def pick(text: str, patterns: list[str]) -> str | None:
    for pattern in patterns:
        match = re.search(pattern, text, flags=re.IGNORECASE)
        if match:
            return match.group(1).strip()
    return None


def extract_location(soup: BeautifulSoup) -> str | None:
    text = soup.get_text("\n", strip=True)

    return pick(text, [
        r"Location:\s*([0-9]{1,3}\|[0-9]{1,3})",
        r"Coordinate:\s*([0-9]{1,3}\|[0-9]{1,3})",
        r"Posizione:\s*([0-9]{1,3}\|[0-9]{1,3})",
    ])


def write_output(coord_to_id: dict[str, int], out_path: Path) -> None:
    lines = [
        "// Auto-generated by generate_twstats_village_map.py",
        "",
        "const VILLAGE_ID_BY_COORD = {",
    ]

    for coord, village_id in sorted(coord_to_id.items()):
        lines.append(f'  "{coord}": {village_id},')

    lines.append("};")
    lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate villages.js coord -> village id map from TWStats."
    )
    parser.add_argument(
        "--base-url",
        default="https://it.twstats.com/it98/index.php?page=village&id={}",
    )
    parser.add_argument("--start", type=int, required=True)
    parser.add_argument("--end", type=int, required=True)
    parser.add_argument("--out", default="villages.js")
    parser.add_argument("--delay", type=float, default=0.5)
    parser.add_argument("--timeout", type=int, default=15)
    args = parser.parse_args()

    if args.start <= 0 or args.end < args.start:
        raise SystemExit("Invalid --start/--end range.")

    coord_to_id: dict[str, int] = {}
    missing = 0
    errors = 0

    for village_id in range(args.start, args.end + 1):
        url = args.base_url.format(village_id)

        try:
            soup = fetch_soup(url, args.timeout)
            location = extract_location(soup)

            if location:
                coord_to_id[location] = village_id
                print(f'"{location}": {village_id},')
            else:
                missing += 1
                print(f"skip {village_id}: no location")

        except requests.RequestException as exc:
            errors += 1
            print(f"skip {village_id}: {exc}")

        if args.delay > 0:
            time.sleep(args.delay)

    out_path = Path(args.out)
    write_output(coord_to_id, out_path)

    print("")
    print(f"Wrote {len(coord_to_id)} villages to {out_path}")
    print(f"Missing location: {missing}")
    print(f"Request errors: {errors}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())